name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <=3.9.16'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_lints: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
